---

- name: (squid_install) [1/5] Squid proxy server is installed
  package:
    name: squid
    state: latest
  register: new_squid_install

- name: (squid_install) [2/5] Squid proxy server is enabled on boot
  service:
    name: squid
    enabled: yes

- name: (squid_install) [3/5] Squid cache dir is present
  file:
    path: /var/spool/squid
    state: directory
    owner: squid
    group: squid

- name: (squid_install) [4/5] New self-signed SSL cert/key pair is generated and deployed
  command: openssl req -x509 -newkey rsa:2048 -nodes -subj "{{ httpd_ssl_cert_subj_string }}" -days 3650 -keyout {{ squid_ssl_key_file }} -out {{ squid_ssl_cert_file }}
  args:
    creates: "{{ squid_ssl_cert_file }}"

- name: (squid_install) [5/5] Create the DH pool
  command: openssl dhparam -out "{{ squid_dhparam_pem_file }}" 4096
  args:
    creates: /etc/ssl/dhparams.pem
