---

- name: (squid_config) [1/1] Template /etc/squid/squid.conf is deployed
  template:
    src: ../templates/squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: 0640
  notify:
    - Restart squid
